export const REMOVE_DATA = 'REMOVE_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const CREATE_DATA = 'CREATE_DATA';

export const GET_TABLE_STARTED = 'FETCH_TABLE_STARTED';
export const GET_TABLE_SUCCESS = 'FETCH_TABLE_SUCCESS';
export const GET_TABLE_ERROR = 'FETCH_TABLE_ERROR';

export const GET_ALL_TABLES_STARTED = 'FETCH_ALL_TABLES_STARTED';
export const GET_ALL_TABLES_SUCCESS = 'FETCH_ALL_TABLES_SUCCESS';
export const GET_ALL_TABLES_ERROR = 'FETCH_ALL_TABLES_ERROR';

export const GET_SEARCH_PLAYER_SUCCESS = 'FETCH_SEARCH_PLAYER_SUCCESS';
export const GET_SEARCH_PLAYER_ERROR = 'FETCH_SEARCH_PLAYER_ERROR';
export const GET_SEARCH_PLAYER_STARTED = 'FETCH_SEARCH_PLAYER_STARTED';

export const GET_SEARCH_PLAYERS_SUCCESS = 'FETCH_SEARCH_PLAYERS_SUCCESS';
export const GET_SEARCH_PLAYERS_ERROR = 'FETCH_SEARCH_PLAYERS_ERROR';
export const GET_SEARCH_PLAYERS_STARTED = 'FETCH_SEARCH_PLAYERS_STARTED';
